# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PavloRybchenko.PakkoCLI
PackageVersion: 1.7.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pakko.exe
ArchiveBinariesDependOnPath: true
Commands:
- pakko
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/pakkoapp-oss/pakko/releases/download/v1.7.2/pakko-win-x64.zip
  InstallerSha256: 17C0D709E4E3ADB5AA5CB23F54EAF555E1C39B308871E75F255E98E240B3C2BB
- Architecture: arm64
  InstallerUrl: https://github.com/pakkoapp-oss/pakko/releases/download/v1.7.2/pakko-win-arm64.zip
  InstallerSha256: 31C69C4D7BD30D02388DDD0FDCA58744B054467AB2812798F42BEC0AF497CF80
ManifestType: installer
ManifestVersion: 1.12.0
